/*
  * More web UI HTML source arrays.
  * This file is auto generated, please don't make any changes manually.
  */ 
 
 // Autogenerated from data/html/settings_tare.htm, do not edit!!
 const char PAGE_settings_tare[] PROGMEM = R"=====(<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta 
name="viewport" content="width=500"><title>Tare Weight</title><script>
var d=document,laprev=55,maxB=1,maxM=5e3,maxPB=4096,bquot=0;function H(){}function B(){window.open("/index","_self")}
</script>%CSS%%SCSS%</head><body onload="S()"><form
 id="form_s" name="startTare" method="post"><div class="helpB"><button 
type="button" onclick="H()">?</button></div><button type="button" onclick="B()">
Back</button><h2>Auto Tare Information</h2><p>
This procedure will guide you throught a small setup with two steps.</p><br><br>
<br><p>
1. Remove all weights from the scale and click on Start, wait until the led is blinking.
</p><p>
2. Take a weight with a measure of 1 (one) Kilogram and place it on the Scale and click on Start. Wait until the led is blinking
</p><button type="button" onclick="B()">Start</button></form></body></html>)=====";
 
 
 // Autogenerated from data/html/settings_general.htm, do not edit!!
 const char PAGE_settings_time[] PROGMEM = R"=====()=====";
 
 